# Generated by Django 3.1.7 on 2021-03-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_description',
            field=models.CharField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
